import type { Instance } from '../api';

const statusClass: Record<Instance['state'], string> = { running: 'bg-emerald-500/15 text-emerald-300', stopped: 'bg-slate-700 text-slate-300', creating: 'bg-amber-500/15 text-amber-300', deleting: 'bg-amber-500/15 text-amber-300', error: 'bg-red-500/15 text-red-300' };

export function InstanceTable({ instances, busyId, onAction, onDelete }: { instances: Instance[]; busyId?: string; onAction: (id: string, action: 'start' | 'stop' | 'restart') => void; onDelete: (id: string) => void }) {
  if (!instances.length) return <div className="rounded-xl border border-dashed border-slate-700 p-12 text-center text-slate-400">No instances yet. Launch your first SSH container.</div>;
  return <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-slate-800 text-slate-400"><th>Instance</th><th>State</th><th>Connection</th><th>Actions</th></tr></thead><tbody>
    {instances.map(instance => { const ssh = instance.ssh.hostPort ? `ssh ${instance.ssh.username}@${instance.ssh.host} -p ${instance.ssh.hostPort}` : ''; const busy = busyId === instance._id; return <tr key={instance._id} className="border-b border-slate-800/70 last:border-0"><td><p className="font-medium text-slate-100">{instance.name}</p><p className="mt-1 text-xs text-slate-500">{new Date(instance.createdAt).toLocaleString()}</p>{instance.lastError && <p className="mt-1 max-w-xs text-xs text-red-300">{instance.lastError}</p>}</td><td><span className={`badge ${statusClass[instance.state]}`}>{instance.state}</span></td><td>{ssh ? <button className="font-mono text-xs text-cyan-300 hover:text-cyan-200" onClick={() => navigator.clipboard.writeText(ssh)} title="Copy SSH command">{ssh} · Copy</button> : <span className="text-slate-500">—</span>}</td><td><div className="flex gap-2">{instance.state === 'stopped' && <button className="button" disabled={busy} onClick={() => onAction(instance._id, 'start')}>Start</button>}{instance.state === 'running' && <><button className="button" disabled={busy} onClick={() => onAction(instance._id, 'stop')}>Stop</button><button className="button" disabled={busy} onClick={() => onAction(instance._id, 'restart')}>Restart</button></>}<button className="button button-danger" disabled={busy} onClick={() => onDelete(instance._id)}>Delete</button></div></td></tr>; })}
  </tbody></table></div>;
}

